language: node_js
node_js:
  - '>=8'
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - yarn
  - greenkeeper-lockfile-update
script:
  - yarn start
after_script:
  - greenkeeper-lockfile-upload
cache:
  yarn: true
  directories:
    - 'node_modules'
